name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PR_NAME: pr-${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}
      - name: Setup packages
        run: |
          npm i
      - name: Unit
        run: npm run test
      - name: Build
        run: npm run build
